### ISSUE TITLE
Opcodes marked as reserved should be avoided for custom instruction set extensions as they might be used by future standard extensions.

### ISSUE THREAD

**Issue by darbaria** [openhwgroup/cv32e40p#457] opened 2020-08-26 13:57 UTC
Reserved ISA encodings are meant not to be used for custom extensions, according to RISC-V v2.2. page 103. I was expecting illegal_insn_o to be flagged, but the core doesn't do this for the following setting:

 parameter PULP_XPULP          =  1,                   
 parameter PULP_CLUSTER       =  0,                  

Changing the setting to:

 parameter PULP_XPULP           =  0,                   
 parameter PULP_CLUSTER       =  0,           

proves the properties exhaustively in formal.

Bug found by: Axiomise formalISA proof kit, and Cadence Jaspergold and Mentor Graphics
[reserved_isa_encodings_not_to_be_used.vcd.gz](https://github.com/openhwgroup/cv32e40p/files/5130257/reserved_isa_encodings_not_to_be_used.vcd.gz)
 Questapropcheck.

VCD for failing assertion is attached. 
This is connected to the discussion being made on: https://github.com/openhwgroup/cv32e40p/issues/452

**Comment by Silabs-ArjanB** [comment] 2020-09-02 13:08
We are closing this issue as it is a duplicate of #452 . Please do not hesitate to re-open this issue if you do not agree that the issue has been handled satisfactorily or if you have further questions.  Thank you for contributing to this core; raising issues will help to improve it.

**Closed by Silabs-ArjanB** 2020-09-02 13:08 UTC
Labels: Component:RTL, PARAM:PULP_XPULP, Type:Bug
